### PR TITLE
Fix environments in factory templates

### PR DESCRIPTION
**Pull request by ashumilova**

### CODE REVIEW

**Comment by riuvshin** [comment]
LGTM

**Comment by mshaposhnik** [comment]
Ok

**Comment by mshaposhnik** [comment]
"defaultEnvName": "wss" -> "defaultEnv": "wss"

**Comment by mshaposhnik** [comment]
"limits": {
              "memory": 2048
            },  
->
"limits": {
              "ram": 2048
            },

**Comment by mshaposhnik** [comment]
Ok nw

**Pull request merged**
