### PR TITLE
CHE-1818: add templates for new environment format

### PR DESCRIPTION
**Pull request by garagatyi**
Add templates for factories for new environment format.
Use separate folder to avoid braking Codenvy prior to 4.8

### CODE REVIEW

**Comment by garagatyi** [comment]
@benoitf @skabashnyuk @ashumilova Please take a look

**Comment by skabashnyuk** [comment]
Ок

**Comment by benoitf** [comment]
I would like to use version number since when format is introduced 
Like 'template-4.8'
But up to you

**Comment by garagatyi** [comment]
Changed folder name to `templates-4.8`

**Pull request merged**
