### PR TITLE
Update factories templates in accordance with CHE-1818

### PR DESCRIPTION
**Pull request by garagatyi**
Needed for codenvy/codenvy#635

### CODE REVIEW

**Comment by benoitf** [comment]
it's not backward compliant ?

**Comment by garagatyi** [comment]
No

**Comment by benoitf** [comment]
Some repositories have their factories.json on it so you mean it will break ?

**Comment by slemeur** [comment]
-1

**Comment by garagatyi** [comment]
@evoevodin is working on a tool that will convert old factories in to new format on factory accepting.
Can you help us to test it by providing possible use-cases for factories with remotely stored workspace configs?

**Comment by benoitf** [comment]
AFAIK if format is changed, it should introduce a new version of factory while I still see v 4.0

**Comment by skabashnyuk** [comment]
we have no time to play with versions right now. It will be done by internal analysis of json content.

**Comment by slemeur** [comment]
-1 to break all existing factories.

**Comment by skabashnyuk** [comment]
> -1 to break all existing factories.

We understand this. As @garagatyi says @evoevodin is working on solution how to handle that.

**Comment by benoitf** [comment]
@skabashnyuk I think it's easier to understand from users that their factory data is not up-to-date if their version number is outdated so that they should try to migrate to a new format

**Comment by skabashnyuk** [comment]
As I said  this is definitely correct and nice idea, we thought about it, but considered too long to implement, so decided to internally analyse json content and transform it to new format on demand.

**Comment by benoitf** [comment]
I don't see why it's too long to implement. Version is here, it means it's useful. Else factory shouldn't have any versions. You may even skip the parsing but at least new factories or migrated one should have this field updated

**Comment by benoitf** [comment]
It's strange to see this PR merged based on feedback that I can see in comments

**Comment by benoitf** [comment]
AFAIk this merge is breaking all UD codenvy instances not running 4.8.0-SNAPSHOT
For example beta.codenvy.com will use right now this template
I guess that when there are breaking changes, new templates need to be added for the new version instead of updating current one

**Comment by garagatyi** [comment]
Yes, I was not aware of that. Thank you for pointing out that. What strategy we should use then? Revert these changes, have them in custom branch or folder and update reference to it in Codenvy UD ?

**Comment by benoitf** [comment]
I suppose your strategy looks good

**Comment by garagatyi** [comment]
Can you comment on that #25

**Pull request merged**
